version: '3.4'

services:
  
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port

  nosql.data:
    image: mongo
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  basket.data:
    image: redis:alpine
    ports:
      - "6379:6379"    # Important: In a production environment your should remove the external port

  rabbitmq:
    #image: rabbitmq:3-management-alpine #problemi con l'utenza guest
    image: rabbitmq:3.7.12-management-alpine
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port