{{- $name := include "catalog-fullimport.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}
{{- $cfgname :=  printf "cfg-%s" $name | trunc 63  }}
{{- $mongo := include "mongo-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $cfgname }}"
  labels:
    app: {{ template "catalog-fullimport.name" . }}
    chart: {{ template "catalog-fullimport.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  catalog__ConnectionString: Server={{ $sqlsrv }};Initial Catalog={{ .Values.inf.sql.catalog.db }};User Id={{ .Values.inf.sql.common.user }};Password={{ .Values.inf.sql.common.pwd }};
  catalog__EnableLoadTest: "{{ .Values.inf.misc.useLoadTest }}"
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: {{ .Values.inf.appinsights.key }}
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  graceperiodmanager__CheckUpdateTime: "{{ .Values.cfg.checkUpdateTime }}"
  graceperiodmanager__GracePeriodTime: "{{ .Values.cfg.gracePeriodTime }}"
  catalog_productSource: "{{ .Values.inf.catalog.url }}"
  search_Url: "{{ .Values.inf.elasticsearch.url }}"
  log_Url: "{{ .Values.inf.logstash.url }}"
  catalog__MongoConnectionString: mongodb://{{ $mongo }}
  catalog__MongoDatabase: {{ .Values.inf.mongo.catalog.database }} 