/*
 * Akeneo PIM API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Catalog.Nosql.Model.Akeneo
{ 
    /// <summary>
    /// Units to which the given metric attributes should be converted when exporting products
    /// </summary>
    [DataContract]
    public partial class Apirestv1channelsConversionUnits : IEquatable<Apirestv1channelsConversionUnits>
    { 
        /// <summary>
        /// Conversion unit code used to convert the values of the attribute &#x60;attributeCode&#x60; when exporting via the channel
        /// </summary>
        /// <value>Conversion unit code used to convert the values of the attribute &#x60;attributeCode&#x60; when exporting via the channel</value>
        [DataMember(Name="attributeCode")]
        public string AttributeCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Apirestv1channelsConversionUnits {\n");
            sb.Append("  AttributeCode: ").Append(AttributeCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Apirestv1channelsConversionUnits)obj);
        }

        /// <summary>
        /// Returns true if Apirestv1channelsConversionUnits instances are equal
        /// </summary>
        /// <param name="other">Instance of Apirestv1channelsConversionUnits to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Apirestv1channelsConversionUnits other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AttributeCode == other.AttributeCode ||
                    AttributeCode != null &&
                    AttributeCode.Equals(other.AttributeCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AttributeCode != null)
                    hashCode = hashCode * 59 + AttributeCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Apirestv1channelsConversionUnits left, Apirestv1channelsConversionUnits right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Apirestv1channelsConversionUnits left, Apirestv1channelsConversionUnits right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
