/*
 * Akeneo PIM API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Catalog.Nosql.Model.Akeneo
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Apirestv1productsAssociationsAssociationTypeCode : IEquatable<Apirestv1productsAssociationsAssociationTypeCode>
    { 
        /// <summary>
        /// Array of groups codes with which the product is in relation
        /// </summary>
        /// <value>Array of groups codes with which the product is in relation</value>
        [DataMember(Name="groups")]
        public List<string> Groups { get; set; }

        /// <summary>
        /// Array of product identifiers with which the product is in relation
        /// </summary>
        /// <value>Array of product identifiers with which the product is in relation</value>
        [DataMember(Name="products")]
        public List<string> Products { get; set; }

        /// <summary>
        /// Array of product model codes with which the product is in relation (only available since the v2.1)
        /// </summary>
        /// <value>Array of product model codes with which the product is in relation (only available since the v2.1)</value>
        [DataMember(Name="product_models")]
        public List<string> ProductModels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Apirestv1productsAssociationsAssociationTypeCode {\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("  ProductModels: ").Append(ProductModels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Apirestv1productsAssociationsAssociationTypeCode)obj);
        }

        /// <summary>
        /// Returns true if Apirestv1productsAssociationsAssociationTypeCode instances are equal
        /// </summary>
        /// <param name="other">Instance of Apirestv1productsAssociationsAssociationTypeCode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Apirestv1productsAssociationsAssociationTypeCode other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Groups == other.Groups ||
                    Groups != null &&
                    Groups.SequenceEqual(other.Groups)
                ) && 
                (
                    Products == other.Products ||
                    Products != null &&
                    Products.SequenceEqual(other.Products)
                ) && 
                (
                    ProductModels == other.ProductModels ||
                    ProductModels != null &&
                    ProductModels.SequenceEqual(other.ProductModels)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Groups != null)
                    hashCode = hashCode * 59 + Groups.GetHashCode();
                    if (Products != null)
                    hashCode = hashCode * 59 + Products.GetHashCode();
                    if (ProductModels != null)
                    hashCode = hashCode * 59 + ProductModels.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Apirestv1productsAssociationsAssociationTypeCode left, Apirestv1productsAssociationsAssociationTypeCode right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Apirestv1productsAssociationsAssociationTypeCode left, Apirestv1productsAssociationsAssociationTypeCode right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
