/*
 * Akeneo PIM API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Catalog.Nosql.Model.Akeneo
{ 
    /// <summary>
    /// Published product attributes values, see &lt;a href&#x3D;&#39;/documentation/resources.html#product-values&#39;&gt;Product values&lt;/a&gt; section for more details
    /// </summary>
    [DataContract]
    public partial class InlineResponse2003Values : IEquatable<InlineResponse2003Values>
    { 
        /// <summary>
        /// Gets or Sets AttributeCode
        /// </summary>
        [DataMember(Name="attributeCode")]
        public List<Apirestv1productsValuesAttributeCode> AttributeCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2003Values {\n");
            sb.Append("  AttributeCode: ").Append(AttributeCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse2003Values)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse2003Values instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2003Values to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2003Values other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AttributeCode == other.AttributeCode ||
                    AttributeCode != null &&
                    AttributeCode.SequenceEqual(other.AttributeCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AttributeCode != null)
                    hashCode = hashCode * 59 + AttributeCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse2003Values left, InlineResponse2003Values right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse2003Values left, InlineResponse2003Values right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
