/*
 * Akeneo PIM API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Catalog.Nosql.Model.Akeneo
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MediaFileList : IEquatable<MediaFileList>
    { 
        /// <summary>
        /// Media file code
        /// </summary>
        /// <value>Media file code</value>
        [DataMember(Name="code")]
        public string Code { get; set; }

        /// <summary>
        /// Original filename of the media file
        /// </summary>
        /// <value>Original filename of the media file</value>
        [DataMember(Name="original_filename")]
        public string OriginalFilename { get; set; }

        /// <summary>
        /// Mime type of the media file
        /// </summary>
        /// <value>Mime type of the media file</value>
        [DataMember(Name="mime_type")]
        public string MimeType { get; set; }

        /// <summary>
        /// Size of the media file
        /// </summary>
        /// <value>Size of the media file</value>
        [DataMember(Name="size")]
        public int? Size { get; set; }

        /// <summary>
        /// Extension of the media file
        /// </summary>
        /// <value>Extension of the media file</value>
        [DataMember(Name="extension")]
        public string Extension { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediaFileList {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  OriginalFilename: ").Append(OriginalFilename).Append("\n");
            sb.Append("  MimeType: ").Append(MimeType).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Extension: ").Append(Extension).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MediaFileList)obj);
        }

        /// <summary>
        /// Returns true if MediaFileList instances are equal
        /// </summary>
        /// <param name="other">Instance of MediaFileList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MediaFileList other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Code == other.Code ||
                    Code != null &&
                    Code.Equals(other.Code)
                ) && 
                (
                    OriginalFilename == other.OriginalFilename ||
                    OriginalFilename != null &&
                    OriginalFilename.Equals(other.OriginalFilename)
                ) && 
                (
                    MimeType == other.MimeType ||
                    MimeType != null &&
                    MimeType.Equals(other.MimeType)
                ) && 
                (
                    Size == other.Size ||
                    Size != null &&
                    Size.Equals(other.Size)
                ) && 
                (
                    Extension == other.Extension ||
                    Extension != null &&
                    Extension.Equals(other.Extension)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Code != null)
                    hashCode = hashCode * 59 + Code.GetHashCode();
                    if (OriginalFilename != null)
                    hashCode = hashCode * 59 + OriginalFilename.GetHashCode();
                    if (MimeType != null)
                    hashCode = hashCode * 59 + MimeType.GetHashCode();
                    if (Size != null)
                    hashCode = hashCode * 59 + Size.GetHashCode();
                    if (Extension != null)
                    hashCode = hashCode * 59 + Extension.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MediaFileList left, MediaFileList right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MediaFileList left, MediaFileList right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
